<h2>Customers</h2>
<br>
<?php if (count($this->success))
    echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));
?>
<?php if (count($this->error))
    echo $this->flashMessenger()->render('error', array('alert', 'alert-danger'));
?>
<form method="post">
    <table class="customersTable" cellpadding="10px">
        <tr>
            <th align="left">Name</th>
            <th align="left">Description</th>
            <th align="left">Actions</th>
        </tr>
        <?php foreach ($this->customers as $customer): ?>
                <tr>
                    <td>
                            <?= $customer->getName() ?>
                    </td>
                    <td>
                        <?= ($customer->getDescription()) ?>
                    </td>
                    <td>
                        <a href="/customers/view/<?= $customer->getId() ?>">
                           view </a>

                        <a href="/customers/update/<?= $customer->getId() ?>">
                            update </a>

                        <a href="/customers/remove/<?= $customer->getId() ?>">
                            remove </a>
                    </td>
                </tr>
        <?php endforeach; ?>
    </table>
<br>
<?php $this->form->get('submit')->setValue('Add New Customer'); ?>
<?= $this->formElement($this->form->get('submit')); ?>
<?= $this->formElementErrors($this->form->get('submit')); ?>
</form>

