<h2>Customers</h2>
 <form method="post">
     <?php foreach ($this->form->getElements() as $element)
     {
         if($element->getName() != 'id' && $element->getName() != 'csrf')
         {
            if($element->getName() != 'submit')
                 echo $this->formLabel($element);
            else {
                echo "<br>";
                $element->setValue('Update');
            }
            echo $this->formElement($element);
            echo $this->formElementErrors($element);
         }
     }
     ?>
 </form>
