<?= $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Sample Application') ?>
    <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
    <?= $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="<?= $this->url('home') ?>">
                    <?= $this->translate('Sample Application') ?></a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>
                            <a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a>
                        </li>
                        <li>
                            <a href="<?= $this->url('customers') ?>"><?= $this->translate('Customers') ?></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <?= $this->content; ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?> by US Signal Company.
                <?= $this->translate('All rights reserved.') ?>
            </p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
</body>
</html>
