<div class="hero-unit">
    <h1><?= $this->translate('Sample Application!') ?></h1>
    <p>Sunday, Sunday, Sunday!</p>
</div>

<div class="row">
    <div class="span4">
        <h3><?= $this->translate('Sclemeel') ?></h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada adipiscing ipsum non
            vestibulum. Nam nulla risus, eleifend non volutpat at, cursus ac justo. Sed quis neque ligula, in
            fermentum velit. Aenean elit risus, vulputate ac venenatis ut, lobortis non eros.
        </p>
    </div>

    <div class="span4">
        <h3><?php echo $this->translate('Schlemazel') ?></h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada adipiscing ipsum non
            vestibulum. Nam nulla risus, eleifend non volutpat at, cursus ac justo. Sed quis neque ligula, in
            fermentum velit. Aenean elit risus, vulputate ac venenatis ut, lobortis non eros.
        </p>
   </div>

   <div class="span4">
       <h3><?php echo $this->translate('Hasenfeffer Incorporated!') ?></h3>
       <p>
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada adipiscing ipsum non
           vestibulum. Nam nulla risus, eleifend non volutpat at, cursus ac justo. Sed quis neque ligula, in
           fermentum velit. Aenean elit risus, vulputate ac venenatis ut, lobortis non eros.
       </p>
   </div>
</div>
